namespace Scripts.StaticData
{
    public enum MonsterTypeId
    {
        Mushroom = 22,
        Bat = 23,
        Bee = 24,
        Chameleon = 25,
        Cyclop = 26,
        Crab = 27,
        WildMan = 28,
        Pirate = 29,
        SpiderDark = 30,
        CyclopRed = 31,
        Devil = 32,
        Werewolf = 33,
        DarkKnight = 34,
        Dragon = 35,
        GolemWhite = 36,
        CyclopWhite =37,
        FallenAngel =38,
        Plant = 39,
        SnailGreen = 40,
        Salamander = 41,
        Lizard = 42,
        MushroomDark = 43,
        Wizard = 44,
        Specter = 45,
        DarkMage = 46,
        Snake = 47,
        WildLeader = 48,
        Rat = 49,
        Necromancer = 50,
        DuskElf = 51,
        Snail = 52,
        Skeleton = 53,
        Orc = 54,
        Golem = 55,
        Demon = 56,
        Worm = 57,
        PlantDark = 58,
        Spider = 59,
        Fishman =60,
        WildGirl = 61,
    }
}
